title: VWork バイブコーディングフレームワーク
description: VWorkは、バイブコーディングを企業内に導入するための作業基盤、実践知、ブログです。
url: "https://katsushi2441.github.io"
baseurl: "/vwork"
lang: ja
author: 株式会社エクスブリッジ
seo_image: "https://exbridge.jp/images/vwork-banner.png"
theme: null
markdown: kramdown
exclude:
  - .git
  - .github
  - packages
  - pyproject.toml
  - LICENSE
defaults:
  - scope:
      path: ""
    values:
      layout: default
